# Generated by Django 5.2.1 on 2025-05-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('frontend', '프론트엔드'), ('backend', '백엔드'), ('none', '선택 안 함')], default='none', max_length=20)),
                ('assigned_position', models.CharField(choices=[('frontend', '프론트엔드'), ('backend', '백엔드'), ('none', '선택 안 함')], default='none', max_length=20)),
                ('leader_preference', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(choices=[('development', '개발'), ('general', '일반')], max_length=20)),
                ('division_type', models.CharField(choices=[('BY_MEMBER_COUNT', '조 당 인원 수'), ('BY_TEAM_COUNT', '조 개수')], max_length=20)),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('max_members', models.PositiveIntegerField(blank=True, null=True)),
                ('total_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('total_members', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('mbti_ie_score', models.FloatField()),
                ('mbti_sn_score', models.FloatField()),
                ('mbti_tf_score', models.FloatField()),
                ('mbti_jp_score', models.FloatField()),
                ('inferred_mbti', models.CharField(blank=True, max_length=4, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teamapp.participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.team'),
        ),
    ]
