# Generated by Django 5.2.1 on 2025-06-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='assigned_team_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_assign_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='inferred_mbti',
            field=models.CharField(default='INFP', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='room_code',
            field=models.CharField(max_length=10),
        ),
    ]
